### ISSUE TITLE
generate_page.sh - errors - don't produce html page

### ISSUE THREAD

**Issue by morgancoxuk** [Dabz/dstat_graph#5]
Hi.

I have just tried this application, it works fine if I open the index.html page and drag/drop a .cvs file into it.

However I cannot find a way of exporting that output correctly, saving the browser output as a PDF misses axis info (probably as its javascript?).

I have tried using the .sh script, however it errors and doesn't produce the right content.
 
i.e

```
 #  mcox@mcox-N552VW:~/src/git/dstat_graph$ ./generate_page.sh test.csv 
 ./generate_page.sh: 24: ./generate_page.sh: [[: not found
```

It does produce html/java script output on the terminal also, however if I try to make a .html page

i.e

 
./generate_page.sh test.csv test.csv > test.html

it produces a page,but when you load it it does the same function as index.html (i.e asks to drag/drop .cvs) 

Can anyone confirm how I can correctly export the graph (with axis info) ?

Regards

**Comment by Dabz** [comment]
```
#  mcox@mcox-N552VW:~/src/git/dstat_graph$ ./generate_page.sh test.csv 
 ./generate_page.sh: 24: ./generate_page.sh: [[: not found
```

`[[` is a bash builtin, but I noticed that the shebang is incorrect in the generate_page.sh script (`/bin/sh`). Could you maybe try `bash ./generate_page.sh test.csv`?  

Concerning the export, I think the easiest is actually to print the webpage as PDF, I tried with firefox, the output is as expected in the PDF.

**Comment by morgancoxuk** [comment]
Thanks that worked (adding bash before the script..)

p.s - cheers for responding so quickly.
